"""geography schema

Revision ID: 0001
Revises:
Create Date: 2026-05-09 16:20:57.933603

"""

from collections.abc import Sequence

import geoalchemy2  # required for Geometry column types in autogenerated DDL
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "code_change",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("old_code", sa.String(length=32), nullable=False),
        sa.Column("new_code", sa.String(length=32), nullable=False),
        sa.Column("change_type", sa.String(length=32), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="geography",
    )
    op.create_table(
        "place",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type", "code", "valid_from", name="uq_place_type_code_validfrom"),
        schema="geography",
    )
    op.create_index(
        "ix_place_geom",
        "place",
        ["geom"],
        unique=False,
        schema="geography",
        postgresql_using="gist",
    )
    op.create_table(
        "place_hierarchy",
        sa.Column("child_id", sa.String(), nullable=False),
        sa.Column("parent_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["geography.place.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["geography.place.id"],
        ),
        sa.PrimaryKeyConstraint("child_id", "parent_id"),
        schema="geography",
    )
    op.create_table(
        "postcode",
        sa.Column("postcode", sa.String(length=8), nullable=False),
        sa.Column("lsoa21", sa.String(), nullable=True),
        sa.Column("msoa21", sa.String(), nullable=True),
        sa.Column("ltla24", sa.String(), nullable=True),
        sa.Column("utla24", sa.String(), nullable=True),
        sa.Column("ward24", sa.String(), nullable=True),
        sa.Column("westminster_constituency_24", sa.String(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["country"],
            ["geography.place.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lsoa21"],
            ["geography.place.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ltla24"],
            ["geography.place.id"],
        ),
        sa.ForeignKeyConstraint(
            ["msoa21"],
            ["geography.place.id"],
        ),
        sa.ForeignKeyConstraint(
            ["region"],
            ["geography.place.id"],
        ),
        sa.ForeignKeyConstraint(
            ["utla24"],
            ["geography.place.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ward24"],
            ["geography.place.id"],
        ),
        sa.ForeignKeyConstraint(
            ["westminster_constituency_24"],
            ["geography.place.id"],
        ),
        sa.PrimaryKeyConstraint("postcode"),
        schema="geography",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("postcode", schema="geography")
    op.drop_table("place_hierarchy", schema="geography")
    op.drop_index("ix_place_geom", table_name="place", schema="geography", postgresql_using="gist")
    op.drop_table("place", schema="geography")
    op.drop_table("code_change", schema="geography")
    # ### end Alembic commands ###
