"""catalogue schema

Revision ID: 0002
Revises: 0001
Create Date: 2026-05-09 18:04:19.822626

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2  # noqa: F401  # required for Geometry column types in autogenerated DDL
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('publisher', sa.Text(), nullable=False),
    sa.Column('publisher_url', sa.Text(), nullable=True),
    sa.Column('dataset_url', sa.Text(), nullable=True),
    sa.Column('licence', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('refresh_cadence', sa.Text(), nullable=True),
    sa.Column('rate_limit', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("mode IN ('loader', 'passthrough')", name='ck_source_mode'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalogue'
    )
    op.create_table('indicator',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=False),
    sa.Column('higher_is', sa.String(length=16), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('available_at', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('refresh_cadence', sa.Text(), nullable=True),
    sa.Column('caveats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('related_keys', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('catalogue_version', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['catalogue.source.id'], ),
    sa.PrimaryKeyConstraint('key'),
    schema='catalogue'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indicator', schema='catalogue')
    op.drop_table('source', schema='catalogue')
    # ### end Alembic commands ###
