"""data schema

Revision ID: 0003
Revises: 0002
Create Date: 2026-05-09 18:05:48.692879

"""

from collections.abc import Sequence

import geoalchemy2  # noqa: F401  # required for Geometry column types in autogenerated DDL
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "loader_run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("rows_written", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["catalogue.source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="data",
    )
    op.create_table(
        "organisation",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("classification", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("registered_address_place_id", sa.String(), nullable=True),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["registered_address_place_id"],
            ["geography.place.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["catalogue.source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="data",
    )
    op.create_table(
        "grant_record",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("funder_id", sa.String(length=64), nullable=True),
        sa.Column("recipient_org_id", sa.String(length=64), nullable=True),
        sa.Column("amount", sa.Numeric(), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("awarded_on", sa.Date(), nullable=True),
        sa.Column("purpose", sa.Text(), nullable=True),
        sa.Column("beneficiary_place_ids", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipient_org_id"],
            ["data.organisation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["catalogue.source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="data",
    )
    op.create_table(
        "indicator_value",
        sa.Column("place_id", sa.String(), nullable=False),
        sa.Column("indicator_key", sa.String(length=128), nullable=False),
        sa.Column("period", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Numeric(), nullable=True),
        sa.Column("value_text", sa.Text(), nullable=True),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("loader_run_id", sa.UUID(), nullable=True),
        sa.Column("caveats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["indicator_key"],
            ["catalogue.indicator.key"],
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["geography.place.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["catalogue.source.id"],
        ),
        sa.PrimaryKeyConstraint("place_id", "indicator_key", "period"),
        schema="data",
    )
    op.create_table(
        "organisation_operates_in",
        sa.Column("organisation_id", sa.String(length=64), nullable=False),
        sa.Column("place_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["data.organisation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["geography.place.id"],
        ),
        sa.PrimaryKeyConstraint("organisation_id", "place_id"),
        schema="data",
    )
    op.create_table(
        "trend_point",
        sa.Column("place_id", sa.String(), nullable=False),
        sa.Column("indicator_key", sa.String(length=128), nullable=False),
        sa.Column("period", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Numeric(), nullable=True),
        sa.Column("revised", sa.Boolean(), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["indicator_key"],
            ["catalogue.indicator.key"],
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["geography.place.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["catalogue.source.id"],
        ),
        sa.PrimaryKeyConstraint("place_id", "indicator_key", "period"),
        schema="data",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trend_point", schema="data")
    op.drop_table("organisation_operates_in", schema="data")
    op.drop_table("indicator_value", schema="data")
    op.drop_table("grant_record", schema="data")
    op.drop_table("organisation", schema="data")
    op.drop_table("loader_run", schema="data")
    # ### end Alembic commands ###
