"""cache and corpus schemas

Revision ID: 0004
Revises: 0003
Create Date: 2026-05-09 18:33:05.134910

"""

from collections.abc import Sequence

import geoalchemy2  # noqa: F401  # required for Geometry column types in autogenerated DDL
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_record",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("consent_version", sa.String(length=32), nullable=False),
        sa.Column("capture_level", sa.String(length=16), nullable=False),
        sa.Column("natural_language_question", sa.Text(), nullable=True),
        sa.Column("tool_called", sa.String(length=64), nullable=False),
        sa.Column("tool_inputs_redacted", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("geography_referenced", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("indicators_returned", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("sources_used", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("result_status", sa.String(length=16), nullable=False),
        sa.Column("error_class", sa.String(length=64), nullable=True),
        sa.Column("asker_sector", sa.String(length=32), nullable=True),
        sa.Column("asker_purpose", sa.Text(), nullable=True),
        sa.Column("marked_useful", sa.Boolean(), nullable=True),
        sa.Column("composed_artefact", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("gap_signals", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("derived_from_question_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["derived_from_question_id"],
            ["corpus.question_record.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="corpus",
    )
    op.create_table(
        "source_cache",
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("cache_key", sa.String(length=512), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["catalogue.source.id"],
        ),
        sa.PrimaryKeyConstraint("source_id", "cache_key"),
        schema="cache",
    )
    op.create_table(
        "raw_record",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["corpus.question_record.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="corpus",
    )
    # ### end Alembic commands ###

    # Restricted role: corpus.raw_record holds pre-sanitisation records
    # for at most 30 days, used only for sanitiser debugging. The main
    # `soundings` user may INSERT but not read; a separate sanitiser role
    # may SELECT and DELETE only.
    # Roles are cluster-global, so they survive a database drop. Create only
    # if absent (mirrors the `DROP ROLE IF EXISTS` in downgrade) so the
    # migration is re-runnable against a fresh database on a shared cluster.
    op.execute(
        "DO $$ BEGIN "
        "IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'soundings_sanitiser') "
        "THEN CREATE ROLE soundings_sanitiser NOLOGIN; END IF; "
        "END $$"
    )
    op.execute("REVOKE ALL ON corpus.raw_record FROM PUBLIC")
    op.execute("GRANT INSERT ON corpus.raw_record TO soundings")
    op.execute("GRANT SELECT, DELETE ON corpus.raw_record TO soundings_sanitiser")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("REVOKE SELECT, DELETE ON corpus.raw_record FROM soundings_sanitiser")
    op.execute("REVOKE INSERT ON corpus.raw_record FROM soundings")
    op.execute("DROP ROLE IF EXISTS soundings_sanitiser")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("raw_record", schema="corpus")
    op.drop_table("source_cache", schema="cache")
    op.drop_table("question_record", schema="corpus")
    # ### end Alembic commands ###
